# Generated by Django 3.1.6 on 2021-02-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Неверный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_page.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Неверный ответ',
                'verbose_name_plural': 'Неверные ответы',
            },
        ),
        migrations.CreateModel(
            name='TrueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_page.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Верный ответ',
                'verbose_name_plural': 'Верные ответы',
            },
        ),
    ]
